version: '3.8'

services:
  app:
    container_name: ${PROJECT_NAME}_app
    image: node:17-alpine
    restart: unless-stopped
    command: sh -c "npm install && npm run start"
    ports:
      - ${PORT}:${INNER_PORT}
    working_dir: /app
    volumes:
      - ./app/:/app
    environment:
      NODE_DOCKER_PORT: ${INNER_PORT}
    depends_on:
      - mysql
    mem_limit: 1024m
    mem_reservation: 256M
    cpus: 4

  mysql:
    image: mysql:5.7
    container_name: ${PROJECT_NAME}_mysql
    restart: unless-stopped
    volumes:
      - v9-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: v_core9
      MYSQL_DATABASE: v_core9

volumes:
  v9-mysql-data: